### ISSUE TITLE
A suspicious grade on WebCAT

### ISSUE THREAD

**Issue by qiongcheng5** [web-cat/web-cat-subsystem-Grader#1]
A student reported that the Web-CAT gave her a full score on the correctness during her second submission attempt, although all test functions actually failed. I also checked her codes in her local laptop and there were errors in her code submission (of 2nd attempt). It should not be 60/60 in the correctness on WebCAT. We have used the Web-CAT for more than six semesters and this is our first time to see this problem. I do not know what caused that.

Could you kindly help check and advise what could be the problem or whether there was any missed or wrong configuration when we set up this new assignment?

**Comment by s-edwards** [comment]
OK, I'll look and see if I can tell you what happened. You may wish to refrain from publishing student identifying information on github issues, since they are publicly visible--you can direct email at webcat@vt.edu for information about how to transmit information that should not be publicly released. I'll let you know what I find out on this one.

**Comment by s-edwards** [comment]
OK, I took a look, and this is an instructor setup error.

First, the assignment is configured without any reference tests at all, so all student solutions automatically satisfy the (missing) instructor reference tests. Second, the plugin settings  have "Include Student Test Results in Grading" unchecked, which means that the coverage requirements are not included in scoring the student. Also, the plugin settings have "Students Must Submit Tests" unchecked, which means student-written tests are purely optional and only for student information. Finally, the code coverage setting is only set at "methods executed", which only requires that each method be called, without checking any other details of the code.

With those settings, the score you see is what I would expect to be produced. If you intended to add instructor-written reference tests, or require students to submit tests and include those tests in grading, please adjust the plugin settings to reflect those choices. Let me know if you need any further assistance.

**Comment by qiongcheng5** [comment]
Thank you very much! I got it.
